env:
  es2021: true
  node: true
extends:
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  no-useless-constructor: "off"
  '@typescript-eslint/no-useless-constructor': "off"
  import/prefer-default-export: "off"
  class-methods-use-this:
    - "error"
    - exceptMethods:
        - up
        - down